#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
重建7个附表的PDF模板，严格按照Excel模板结构
"""

with open('威特电梯厂检调试记录单v2.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 替换范围：
# - 起始：行6665 (0-based 6664): "// 根据attNum生成对应附表"
# - 结束：行7214 (0-based 7213): "  }" (最后一个附表if分支的结束})
# 保留：页脚部分（行7216-7218）、return h;、}

START_IDX = 6664  # 0-based，包含这一行
END_IDX = 7213    # 0-based，包含这一行

print(f"替换范围: 行{START_IDX+1} 到 行{END_IDX+1}")
print(f"共 {END_IDX - START_IDX + 1} 行")

# 生成新的附表代码
new_code_lines = []

def add(code):
    new_code_lines.append(code)

# ========== 开头 ==========
add("  // 根据attNum生成对应附表（按Excel模板结构）")
add("  if (attNum === 1) {")
add("    // === 附表1: 电梯门间隙、门锁啮合长度及地坎间距检验记录 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表1 电梯门间隙、门锁啮合长度及地坎间距检验记录</div>';")
add("")
add("    // 主表格 - 13列，多层表头")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:7.5px;table-layout:fixed;\">';")
add("")
add("    // 第一层表头")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"4\">检验项目<br>编号与内容</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">A1.2.7.1</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"6\">A1.2.7.2门间隙</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"4\">A1.2.7.8（2）<br>门锁啮合长度</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">A1.2.7.10</td>';")
add("    h += '</tr>';")
add("")
add("    // 第二层表头")
add("    h += '<tr style=\"background:#f5f5f5;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">门地坎距离</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"5\">A1.2.7.2(1)</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"3\">A1.2.7.2(2)<br>门扇间施力间隙</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"3\">轿门门刀与层门地坎间隙</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"3\">层门门锁滚轮与轿厢地坎间隙</td>';")
add("    h += '</tr>';")
add("")
add("    // 第三层表头 (空行用于合并)")
add("    h += '<tr style=\"background:#fafafa;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"5\"></td>';")
add("    h += '</tr>';")
add("")
add("    // 第四层表头 - 细分项目")
add("    h += '<tr style=\"background:#fafafa;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">门扇间间隙</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">门扇与立柱、门楣间隙</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">门扇与地坎间隙</td>';")
add("    h += '</tr>';")
add("")
add("    // 判断标准行 (2行合并)")
add("    h += '<tr style=\"text-align:center;font-size:7px;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;font-weight:bold;\" rowspan=\"2\">判断标准</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">≤35<br>左右偏差小于1/1000</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"5\">乘客电梯：3-6<br>载货电梯：3-10<br>左右偏差不超过1mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">旁开门：≤30<br>中分门：≤45</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≥7</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≥5</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≥5</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;font-size:7px;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"5\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '</tr>';")
add("")
add("    // 构建数据行")
add("    var laygateList = att1.laygate || [];")
add("    var dataRows = [];")
add("    // 轿门1、2")
add("    dataRows.push({label: '轿门1', isCar: true, idx: 0});")
add("    dataRows.push({label: '轿门2', isCar: true, idx: 1});")
add("    // 层门")
add("    var laygateCount = Math.max(laygateList.length, 10);")
add("    for (var li = 0; li < laygateCount; li++) {")
add("      var layerName = (laygateList[li] && laygateList[li].name) ? laygateList[li].name : ((li+1) + '层');")
add("      dataRows.push({label: layerName, isCar: false, idx: li});")
add("    }")
add("")
add("    // 获取数据的辅助函数")
add("    function getAtt1Val(isCar, rowIdx, colIdx) {")
add("      if (isCar) {")
add("        var carArr = att1.cargate && att1.cargate[rowIdx] ? att1.cargate[rowIdx] : [];")
add("        return carArr[colIdx] || '';")
add("      } else {")
add("        if (laygateList[rowIdx] && laygateList[rowIdx].data) {")
add("          return laygateList[rowIdx].data[colIdx] || '';")
add("        }")
add("        return '';")
add("      }")
add("    }")
add("")
add("    // 数据行 - 检验位置及测量数据（第一列纵向合并）")
add("    dataRows.forEach(function(row, ri) {")
add("      var lbl = row.label;")
add("      var isCar = row.isCar;")
add("      var idx = row.idx;")
add("      h += '<tr style=\"text-align:center;\">';")
add("      // 检验位置列（第一列合并）")
add("      if (ri === 0) {")
add("        h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"' + dataRows.length + '\">检验位置及测量数据</td>';")
add("      }")
add("      // 位置名称 + 左/右（2列，用位置列占第一列，第二列空？不对，Excel中位置列是一列）")
add("      // 修正：位置列就是一列位置名")
add("      h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;\" colspan=\"2\">' + escHtml(lbl) + '</td>';")
add("      // 门扇间间隙")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 1)) + '</td>';")
add("      // 门扇与立柱门楣间隙（2列：左/右）")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 2)) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 3)) + '</td>';")
add("      // 门扇与地坎间隙（2列：左/右）")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 4)) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 5)) + '</td>';")
add("      // 门扇间施力间隙")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 6)) + '</td>';")
add("      // 门锁啮合长度")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 7)) + '</td>';")
add("      // 轿门门刀与层门地坎间隙")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 8)) + '</td>';")
add("      // 层门门锁滚轮与轿厢地坎间隙")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(getAtt1Val(isCar, idx, 9)) + '</td>';")
add("      h += '</tr>';")
add("    });")
add("")
add("    h += '</table>';")
add("")

# ========== 附表2 ==========
add("  } else if (attNum === 2) {")
add("    // === 附表2: 缓冲距、顶部空间和底坑空间检测记录 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表2   缓冲距、顶部空间和底坑空间检测记录</div>';")
add("")
add("    // 顶部参数行（10列布局）")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;margin-bottom:4px;\">';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:20%;background:#f0f0f0;font-weight:bold;\" rowspan=\"2\">轿厢缓冲距</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\" rowspan=\"2\">' + escHtml(att2.轿厢缓冲距||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;background:#f0f0f0;font-weight:bold;\">对重缓冲距</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\">' + escHtml(att2.对重缓冲距||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:15%;background:#f0f0f0;font-weight:bold;\" rowspan=\"2\">缓冲器压缩行程</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:7%;background:#f0f0f0;font-weight:bold;\">轿厢</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:7%;\">mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:7%;background:#f0f0f0;font-weight:bold;\">对重</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:7%;\">mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:13%;background:#f0f0f0;font-weight:bold;\">检验结果</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#f0f0f0;font-weight:bold;\">最大允许值</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\">mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#f0f0f0;font-weight:bold;\">' + escHtml(att2.轿厢压缩行程||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#f0f0f0;font-weight:bold;\">' + escHtml(att2.对重压缩行程||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\"></td>';")
add("    h += '</tr>';")
add("    h += '</table>';")
add("")
add("    // 井道顶部空间 + 底坑空间 合并表格")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:7.5px;table-layout:fixed;\">';")
add("")
add("    // 表头")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\" rowspan=\"2\">项目</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\" rowspan=\"2\">上端站平层时</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:20%;\" colspan=\"2\">对重完全压在缓冲器上时轿门与层门地坎距离</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\" rowspan=\"2\">检验结果</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"background:#f5f5f5;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">m</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '</tr>';")
add("")
add("    // 井道顶部空间 - 大类行")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#e8e8e8;font-weight:bold;text-align:center;\" rowspan=\"6\">井道顶部空间</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\">m</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '</tr>';")
add("")
add("    var topItems = [")
add("      {label:'①轿厢导轨进一步制导行程≥0.1＋0.035v²（m）', key:'s1'},")
add("      {label:'②位于轿厢投影部分的井道顶最低部件的水平面与轿顶最高可站人面积水平面之间的自由垂直距离≥1.0+0.035v（m）', key:'s2'},")
add("      {label:'③井道顶最低部件与固定在轿顶部件最高部分之间的自由垂直距离≥0.3+0.035v（m）', key:'s3'},")
add("      {label:'④井道顶的最低部件与导靴或滚轮、悬挂装置端接装置附件、垂直滑动门的横梁或者部件的最高部分之间的自由垂直距离≥0.1+0.035v²（m）', key:'s4'},")
add("      {label:'⑤轿顶空间（≥0.5m×0.6m×0.8m）', key:'s5'}")
add("    ];")
add("    topItems.forEach(function(item) {")
add("      h += '<tr>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px 2px;\">' + escHtml(item.label) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\">' + escHtml(att2.顶部空间[item.key]||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '</tr>';")
add("    });")
add("")
add("    // 底坑空间 - 大类行")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#e8e8e8;font-weight:bold;text-align:center;\" rowspan=\"7\">底坑空间</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\">m</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("    h += '</tr>';")
add("")
add("    var pitItems = [")
add("      {label:'①底坑底与轿厢最低部件之间的自由垂直距离≥0.5m', key:'p1'},")
add("      {label:'②对重导轨进一步制导行程≥0.1+0.035v²（m）', key:'p2'}")
add("    ];")
add("    pitItems.forEach(function(item) {")
add("      h += '<tr>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px 2px;\">' + escHtml(item.label) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\">' + escHtml(att2.底坑空间[item.key]||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '</tr>';")
add("    });")
add("")
add("    // 第③项（特殊：两行列合并）")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px 2px;\" rowspan=\"2\">③下述水平距离在0.15m之内时，底坑底与轿厢最低部件之间的自由垂直距离≥0.1m</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\" rowspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;font-size:7px;\">1）水平　　m<br>垂直　　m</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\" rowspan=\"2\"></td>';")
add("    h += '</tr>';")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;font-size:7px;\">2）水平　　m<br>垂直　　m</td>';")
add("    h += '</tr>';")
add("")
add("    // 第④⑤项")
add("    var pitItems2 = [")
add("      {label:'④底坑中固定的最高部件和轿厢的最低部件之间的自由垂直距离≥0.3m', key:'p4'},")
add("      {label:'⑤轿底空间（≥0.5m×0.6m×1.0m）', key:'p5'}")
add("    ];")
add("    pitItems2.forEach(function(item) {")
add("      h += '<tr>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px 2px;\">' + escHtml(item.label) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\">' + escHtml(att2.底坑空间[item.key]||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;text-align:center;\"></td>';")
add("      h += '</tr>';")
add("    });")
add("")
add("    h += '</table>';")
add("")
add("    // 备注")
add("    h += '<div style=\"margin-top:4px;font-size:7px;line-height:1.4;\">';")
add("    h += '<b>备注：</b>';")
add("    h += '(1) 当曳引驱动电梯驱动主机的减速是按照规定被监控时，对于非斜行电梯，0.035可以用按轿厢或者对重触及缓冲器时的速度减小来代替；<br>';")
add("    h += '(2) 对于具有补偿绳及补偿绳张紧轮和防跳装置的曳引驱动电梯，0.035v²的值可以用张紧轮可能的移动量再加上轿厢行程的1/500或者0.20m（取二者中的较大者）来代替。';")
add("    h += '</div>';")
add("")

# ========== 附表3 ==========
add("  } else if (attNum === 3) {")
add("    // === 附表3: 导轨工作面铅垂度测量表 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表 3  导轨工作面铅垂度测量表</div>';")
add("")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;\">';")
add("    // 表头")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">序     号</td>';")
add("    for (var mi = 1; mi <= 10; mi++) {")
add("      h += '<td style=\"border:1px solid #000;padding:2px;\">' + mi + '</td>';")
add("    }")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\">最大偏差</td>';")
add("    h += '</tr>';")
add("")
add("    // 轿厢左导轨")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" rowspan=\"2\">轿厢</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;\">左导轨</td>';")
add("    for (var c3l = 0; c3l < 10; c3l++) {")
add("      var rowL = att3.rows[c3l] || {carL:''};")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(rowL.carL||'') + '</td>';")
add("    }")
add("    h += '<td style=\"border:1px solid #000;padding:1px;font-weight:bold;\">' + escHtml(att3.maxDev.carL||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    // 轿厢右导轨")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;\">右导轨</td>';")
add("    for (var c3r = 0; c3r < 10; c3r++) {")
add("      var rowR = att3.rows[c3r] || {carR:''};")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(rowR.carR||'') + '</td>';")
add("    }")
add("    h += '<td style=\"border:1px solid #000;padding:1px;font-weight:bold;\">' + escHtml(att3.maxDev.carR||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    // 对重左导轨")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" rowspan=\"2\">对重</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;\">左导轨</td>';")
add("    for (var w3l = 0; w3l < 10; w3l++) {")
add("      var rowWL = att3.rows[w3l] || {weightL:''};")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(rowWL.weightL||'') + '</td>';")
add("    }")
add("    h += '<td style=\"border:1px solid #000;padding:1px;font-weight:bold;\">' + escHtml(att3.maxDev.weightL||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    // 对重右导轨")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;\">右导轨</td>';")
add("    for (var w3r = 0; w3r < 10; w3r++) {")
add("      var rowWR = att3.rows[w3r] || {weightR:''};")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(rowWR.weightR||'') + '</td>';")
add("    }")
add("    h += '<td style=\"border:1px solid #000;padding:1px;font-weight:bold;\">' + escHtml(att3.maxDev.weightR||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    // 底部说明行")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-size:7px;\" colspan=\"13\">每列导轨工作面每5m铅垂线测量值间的相对最大偏差均不大于下列数值：轿厢导轨和设有安全钳的T型对重导轨为1.2mm；不设安全钳的T型对重导轨为2mm。</td>';")
add("    h += '</tr>';")
add("")
add("    h += '</table>';")
add("")

# ========== 附表4 ==========
add("  } else if (attNum === 4) {")
add("    // === 附表4: 导轨顶面距离测量 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表 4   导轨顶面距离测量</div>';")
add("")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;\">';")
add("")
add("    // 第一行：基准值")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#f0f0f0;font-weight:bold;\" colspan=\"2\">轿厢导轨面距基准：</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:10%;\">' + escHtml(att4.refCar||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\">mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:12%;\">（0~﹢2）</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#f0f0f0;font-weight:bold;\" colspan=\"2\">对重导轨面距基准：</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:10%;\">' + escHtml(att4.refWeight||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:8%;\">mm</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:12%;\">（0~﹢3）</td>';")
add("    h += '</tr>';")
add("")
add("    // 数据行：5行，每行左右各2个测点（1-5和6-10）")
add("    var att4rows = att4.rows || [];")
add("    for (var r4 = 0; r4 < 5; r4++) {")
add("      var row4a = att4rows[r4] || {car:'', weight:''};")
add("      var row4b = att4rows[r4 + 5] || {car:'', weight:''};")
add("      h += '<tr style=\"text-align:center;\">';")
add("      // 左半：轿厢")
add("      h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;width:5%;\">' + (r4+1) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:10%;\">' + escHtml(row4a.car||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;width:5%;\">' + (r4+6) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:10%;\">' + escHtml(row4b.car||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:5%;\"></td>';")
add("      // 右半：对重")
add("      h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;width:5%;\">' + (r4+1) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:10%;\">' + escHtml(row4a.weight||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;width:5%;\">' + (r4+6) + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:10%;\">' + escHtml(row4b.weight||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;width:5%;\"></td>';")
add("      h += '</tr>';")
add("    }")
add("")
add("    // 最大偏差行")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-weight:bold;\" colspan=\"2\">最大偏差</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"3\">' + escHtml(att4.maxDev.car||'') + '</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-weight:bold;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"3\">' + escHtml(att4.maxDev.weight||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    h += '</table>';")
add("")

# ========== 附表5 ==========
add("  } else if (attNum === 5) {")
add("    // === 附表5: 电梯平衡系数检验记录 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表 5    电梯平衡 系数检验记录</div>';")
add("")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;\">';")
add("    // 载重量行（合并）")
add("    h += '<tr style=\"text-align:center;background:#f0f0f0;font-weight:bold;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:12%;\" rowspan=\"2\">载重量</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:12%;\" rowspan=\"2\">重量（Kg）<br>额载百分比（﹪）</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">0.3</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">0.4</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">0.45</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">0.5</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"2\">0.6</td>';")
add("    h += '</tr>';")
add("")
add("    // 运行方向行")
add("    h += '<tr style=\"text-align:center;background:#f5f5f5;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '</tr>';")
add("")
add("    // 电流行")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;font-weight:bold;\" colspan=\"2\">电  流（A）</td>';")
add("    var upCurrents = att5.电流['电流上行'] || ['','','','',''];")
add("    var downCurrents = att5.电流['电流下行'] || ['','','','',''];")
add("    for (var ci5 = 0; ci5 < 5; ci5++) {")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(upCurrents[ci5]||'') + '</td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(downCurrents[ci5]||'') + '</td>';")
add("    }")
add("    h += '</tr>';")
add("")
add("    // 测试结果行")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;background:#fafafa;font-weight:bold;\" colspan=\"2\">测试结果</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"10\">平衡系数：' + escHtml(att5.平衡系数||'') + '</td>';")
add("    h += '</tr>';")
add("")
add("    // 空白行（填充到合适高度，留给曲线图）")
add("    for (var blank5 = 0; blank5 < 8; blank5++) {")
add("      h += '<tr style=\"height:14px;\">';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"10\"></td>';")
add("      h += '</tr>';")
add("    }")
add("")
add("    h += '</table>';")
add("")
add("    // 电流曲线示意图（放在表格下方）")
add("    var upArr = [], downArr = [];")
add("    for (var ci = 0; ci < 5; ci++) {")
add("      upArr.push(parseFloat(upCurrents[ci]) || 0);")
add("      downArr.push(parseFloat(downCurrents[ci]) || 0);")
add("    }")
add("    var maxC = Math.max.apply(null, upArr.concat(downArr, [10]));")
add("    function calcY(v) { return 85 - (v / maxC) * 70; }")
add("    var xPts = ['10%','28%','46%','64%','82%'];")
add("    var upPoints = xPts.map(function(x, i) { return x + ',' + calcY(upArr[i]) + '%'; }).join(' ');")
add("    var downPoints = xPts.map(function(x, i) { return x + ',' + calcY(downArr[i]) + '%'; }).join(' ');")
add("")
add("    h += '<div style=\"margin-top:6px;border:1px solid #000;padding:8px 8px 20px 8px;position:relative;\">';")
add("    h += '<div style=\"font-size:8px;font-weight:bold;margin-bottom:4px;\">电流曲线示意图：</div>';")
add("    h += '<div style=\"position:relative;width:100%;height:100px;border-left:1px solid #999;border-bottom:1px solid #999;\">';")
add("    // X轴标签")
add("    var labels5 = ['30%','40%','45%','50%','60%'];")
add("    labels5.forEach(function(lbl, i) {")
add("      h += '<div style=\"position:absolute;left:' + xPts[i] + ';bottom:-16px;font-size:7px;color:#666;transform:translateX(-50%);\">' + lbl + '</div>';")
add("    });")
add("    // Y轴标签")
add("    h += '<div style=\"position:absolute;left:-28px;top:45%;font-size:7px;color:#666;\">电流(A)</div>';")
add("    // 曲线")
add("    h += '<svg width=\"100%\" height=\"100%\" style=\"position:absolute;top:0;left:0;\">';")
add("    h += '<polyline points=\"' + upPoints + '\" fill=\"none\" stroke=\"#3182ce\" stroke-width=\"1.5\"/>';")
add("    h += '<polyline points=\"' + downPoints + '\" fill=\"none\" stroke=\"#e53e3e\" stroke-width=\"1.5\"/>';")
add("    // 数据点")
add("    for (var dp = 0; dp < 5; dp++) {")
add("      h += '<circle cx=\"' + xPts[dp] + '\" cy=\"' + calcY(upArr[dp]) + '%\" r=\"2\" fill=\"#3182ce\"/>';")
add("      h += '<circle cx=\"' + xPts[dp] + '\" cy=\"' + calcY(downArr[dp]) + '%\" r=\"2\" fill=\"#e53e3e\"/>';")
add("    }")
add("    h += '</svg>';")
add("    // 图例")
add("    h += '<div style=\"position:absolute;top:2px;right:10px;font-size:7px;\">';")
add("    h += '<span style=\"color:#3182ce;\">—— 上行</span>&nbsp;&nbsp;';")
add("    h += '<span style=\"color:#e53e3e;\">—— 下行</span>';")
add("    h += '</div>';")
add("    h += '</div>';")
add("    h += '</div>';")
add("")

# ========== 附表6 ==========
add("  } else if (attNum === 6) {")
add("    // === 附表6: 钢丝绳张力测试记录 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表 6   钢丝绳张力测试记录</div>';")
add("")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;\">';")
add("    // 表头")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\">钢丝绳序号</td>';")
add("    for (var f6 = 1; f6 <= 8; f6++) {")
add("      h += '<td style=\"border:1px solid #000;padding:2px;\">F' + f6 + '</td>';")
add("    }")
add("    h += '</tr>';")
add("")
add("    // 张力值行")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;background:#fafafa;\">张力值</td>';")
add("    for (var fj = 1; fj <= 8; fj++) {")
add("      h += '<td style=\"border:1px solid #000;padding:1px;\">' + escHtml(att6['F'+fj]||'') + '<br>N</td>';")
add("    }")
add("    h += '</tr>';")
add("")
add("    // 张力平均值行（公式说明）")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-weight:bold;\">张力平均值</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"8\">（最大值-最小值）/张力平均值=张力偏差</td>';")
add("    h += '</tr>';")
add("")
add("    // 张力偏差计算")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-weight:bold;\">张力偏差计算</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"8\">张力值偏差:     /      =</td>';")
add("    h += '</tr>';")
add("")
add("    // 张力判定")
add("    h += '<tr>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;font-weight:bold;\">张力判定</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" colspan=\"8\">张力偏差计算值:         结论:</td>';")
add("    h += '</tr>';")
add("")
add("    h += '</table>';")
add("")

# ========== 附表7 ==========
add("  } else if (attNum === 7) {")
add("    // === 附表7: 乘客电梯噪声测试记录表 ===")
add("    h += '<div style=\"font-size:10px;font-weight:bold;text-align:center;margin-bottom:4px;\">附表 7  乘客电梯噪声测试记录表（单位：dB(A)）</div>';")
add("")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed;\">';")
add("    // 表头")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:22%;\">测量项目</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:15%;\">测量位置</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:23%;\" colspan=\"2\">测量值</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:15%;\">背景</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:25%;\">修正后</td>';")
add("    h += '</tr>';")
add("")
add("    // 开关门过程噪声 - 层站")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" rowspan=\"4\">开关门过程噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\">层站</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">开门</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"4\">最大值：</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">关门</td>';")
add("    h += '</tr>';")
add("    // 开关门过程噪声 - 轿厢")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\">轿厢</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">开门</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\"></td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">关门</td>';")
add("    h += '</tr>';")
add("")
add("    // 运行中轿厢内噪声")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" rowspan=\"2\">运行中轿厢内噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">上行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\">最大值：</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">下行</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '</tr>';")
add("")
add("    // 机房噪声")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\" rowspan=\"3\">机房<br>噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">1</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"3\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"3\">平均值：</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">2</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">3</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '</tr>';")
add("")
add("    // 无机房噪声")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;\">无机房噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">层门处</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\"></td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">最大值：</td>';")
add("    h += '</tr>';")
add("")
add("    h += '</table>';")
add("")
add("    // 额定速度对比表")
add("    h += '<div style=\"margin-top:6px;\">';")
add("    h += '<table style=\"width:100%;border-collapse:collapse;font-size:7.5px;table-layout:fixed;\">';")
add("    h += '<tr style=\"background:#f0f0f0;font-weight:bold;text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:22%;\">额定速度υ</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:18%;\">机房噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:20%;\" colspan=\"2\">轿厢内噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:15%;\">开关门噪声</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:2px;width:25%;\">无机房电梯层门处噪声</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">υ≤2.5m/s</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≤80dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">≤55dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≤65dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≤65dB</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">2.5m/s＜υ≤6.0m/s</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≤85dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"2\">≤60dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">≤65dB</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" rowspan=\"2\">不超过制造单位的允许值。制造单位未规定的，按≤65dB。</td>';")
add("    h += '</tr>';")
add("    h += '<tr style=\"text-align:center;\">';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\">υ＞6.0m/s</td>';")
add("    h += '<td style=\"border:1px solid #000;padding:1px;\" colspan=\"4\">不超过制造单位的允许值。制造单位未规定的，按下表规定加5dB。</td>';")
add("    h += '</tr>';")
add("    h += '</table>';")
add("    h += '</div>';")
add("")

# ========== 结尾 ==========
add("  }")

# 验证
print(f"生成新代码行数: {len(new_code_lines)}")
print(f"原代码行数: {END_IDX - START_IDX + 1}")

# 执行替换
new_lines = lines[:START_IDX] + [l + '\n' for l in new_code_lines] + lines[END_IDX+1:]

with open('威特电梯厂检调试记录单v2.html', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f"替换完成！总行数: {len(new_lines)}")

# 验证文件大小
import os
size = os.path.getsize('威特电梯厂检调试记录单v2.html')
print(f"文件大小: {size} 字节")
